### ISSUE TITLE
Add repo field to package.json

### ISSUE THREAD

**Issue by feross** [mooz/node-icu-charset-detector#21]
There's no link to GitHub on https://www.npmjs.com/package/node-icu-charset-detector and this makes it hard to find this repo.

**Comment by mooz** [comment]
Strange. Though we have both `repository` field and `homepage` field, npmjs.org doesn't displays the link to this repository. I'm not sure whether the cause is on npmjs side or this package side.

**Comment by feross** [comment]
I've found that https:// urls don't show up. Try a git:// url, like this: https://github.com/feross/webtorrent/blob/master/package.json#L103

**Comment by mooz** [comment]
Thanks for the info. I've corrected the package.json.
