### ISSUE TITLE
Problem compiling for osx

### ISSUE THREAD

**Issue by hrajchert** [mooz/node-icu-charset-detector#5]
Ive installed icu4c using brew in osx, but when I try to install node-icu-charset-detector I get:

../node-icu-charset-detector.cpp:5:10: fatal error: 'unicode/ucsdet.h' file not found

**Comment by yamsellem** [comment]
A little note here (because I lost half an hour on a @syohex typo ;-).

```
brew install icu4c
brew link icu4c
```

Seems obvious, right, but copy pasting "icu4k" without checking made me lost a lot of time.

**Comment by syohex** [comment]
Ah, sorry.

**Comment by yamsellem** [comment]
There's absolutely no problem: that was my fault ;-).
@syohex you clearly fix the issue, so thanks again ;-).
